<?php

/**
 * ZipCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZipCodeTable extends PluginZipCodeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZipCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ZipCode');
    }
}