<?php

/**
 * CustomerRequisitionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomerRequisitionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustomerRequisitionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CustomerRequisition');
    }
}