<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Payment extends BasePayment
{
  public function setAmount($v)
  {
    $v = round($v, PropertyTable::get('currency_decimals', 2));

    return $this->_set('amount', $v);
  }

  public function fullpayment()
  {
    if($this->_get('invoice_id'))
    {
      $invoice = Doctrine::getTable('Invoice')->find($this->_get('invoice_id'));
      if($invoice->gross_amount - $invoice->paid_amount <= 0)
      {
        return false;
      }
      $this->setAmount($invoice->gross_amount - $invoice->paid_amount);
      return true;
    }
    return false;
  }
  
  public function postSave($event)
  {
    $this->getInvoice()->checkStatus()->save();
  }
  
  public function postDelete($event)
  {
    $this->getInvoice()->checkStatus()->save();
  }
  
  public function getAmount()
  {
    return (float) $this->_get('amount');
  }
}