all:
  metas:
    title:     30invoice - Clienti
  components:
    searchForm: [search, customerForm]
    
indexSuccess:
  stylesheets: [ /sfFormExtraPlugin/css/jquery.autocompleter.css ]
  javascripts:
    - core/table.js
    
editSuccess:
  javascripts:
    - invoice