<?php

/**
 * ImportCustomerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImportCustomerTable extends PluginImportCustomerTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImportCustomerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImportCustomer');
    }
}