<?php

/**
 * PluginZipCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginZipCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginZipCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginZipCode');
    }
}