<?php

/**
 * PluginImportCustomerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginImportCustomerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginImportCustomerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginImportCustomer');
    }
}