<?php

/**
 * PluginImportItemsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginImportItemsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginImportItemsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginImportItems');
    }
}