<?php

/**
 * PluginImportInvoiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginImportInvoiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginImportInvoiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginImportInvoice');
    }
}